### ISSUE TITLE
Compilation of discuss and reject issues

### ISSUE THREAD

**Issue by Quasant** [AY2425S1-CS2103-F13-4/tp#363]
### Moved from rejected to fixing an actual problem/improvement in UG
- [x] #351 
- [x] #343 
- [x] #359

### REJECTED CAUSE INVALID- (Feel free to re-open)
- [x] #338, 3/5 vote
- [x] #358, 2/5 vote 
- [x] #361, force rejected by JB (found src disproving it)
- [x] #312, 2/5 vote  
  - However, this opens up an issue #372 

### REJECTED CAUSE LOW IMPACT
- [x] #272, force rejected by Ben (can't do anything)
- [x] #270, 3/5 vote + other reasons
- [x] #262, 3/5 vote + other reasons (click on issue to see) 
- [x] #275, force rejected by Ben, defensible 
- [x] #300, force rejected by Ben, defensible?
- [x] #264, force rejected by Ben, insufficient details by tester 
- [x] #292
  - related to the rejected #312 
  - related to issue #372
